#%RAML 1.0 Trait
headers:
  X-Correlation-ID:
    description: |
      Consumer system's tracking ID for this request (if any).
      This is optional and purely for troubleshooting / analysis purposes.
    type: string
    required: false