#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f7b77654-66fd-495c-b990-167cd6d610b0/ # 
title: sys-weather
description: This system API provides list of Cities in a country and weather details for a city. 
version: v1
securedBy: [lib.basic]
types:
  cities: !include DataTypes/cities.raml
  weather: !include DataTypes/weather.raml
uses: 
  lib: exchange_modules/e55e13cc-f60e-40fb-b321-986e8f2c11b8/raml-reusable-assets/1.0.0/raml-reusable-assets.raml
/{version}:
  /about:
    type: 
      lib.item:
        typeName: lib.about
    get:
      displayName: Information about application
      description: This end point provides information about Mule application which can be used to determine availablity of the application.
      is: [lib.traceable, lib.hasErrors]
  /cities:
    /{country}:
      type:
        lib.item:
          typeName: cities
      get:
        displayName: get cities by Country
        description: get cities by Country
        is: [lib.traceable, lib.hasErrors]
  /weather:
    type:
      lib.item:
        typeName: weather
    get:
      queryParameters:
        city: string
      displayName: get weather of the city
      description: get weather of the city
      is: [lib.traceable, lib.hasErrors]
      
        

      

    
        
          
      


  


  